services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: crypto_db
    environment:
      POSTGRES_USER: crypto_user
      POSTGRES_PASSWORD: crypto_pass_123
      POSTGRES_DB: cryptoai
    ports:
      - "5432:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - crypto-net

  data-collector:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: crypto_data_collector
    depends_on:
      - timescaledb
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - crypto-net
    volumes:
      - ./backend/logs:/app/logs

networks:
  crypto-net:
    driver: bridge

volumes:
  timescale_data: